[build]
  command = "npm run build"
  publish="https://github.com/DolphinRidz/react_snake_game.git/build"
  base = "https://github.com/DolphinRidz/react_snake_game.git"
  [[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200